AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lotto-checker
Parameters:
  AppHostUrl:
    Type: String
    Description: URL where app will be hosted. To be added as a CORS allowed origin.

Globals:
  Function:
    Timeout: 3

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: LottoChecker API
      CorsConfiguration: # true
        AllowMethods:
          - GET
        AllowHeaders:
          - "*"
        AllowOrigins:
          - "*"
        ExposeHeaders:
          - "*"
      Auth:
        Authorizers:
          OAuth2Authorizer:
            AuthorizationScopes:
              - email
            JwtConfiguration:
              Issuer: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}
              Audience:
                - !Ref UserPoolWebClient
            IdentitySource: "$request.header.Authorization"
        DefaultAuthorizer: OAuth2Authorizer

  LottoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lotto/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          APP_HOST_URL: !Ref AppHostUrl
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /lotto/WinningNumbers/{state}/{game}
            Method: GET

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: LottoCheckerUserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false

  UserPoolWebClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: LottoCheckerFrontend
      GenerateSecret: false
      CallbackURLs:
        - !Ref AppHostUrl
        - http://localhost:8080
      LogoutURLs:
        - !Ref AppHostUrl
        - http://localhost:8080
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref AWS::StackName
      UserPoolId: !Ref UserPool

Outputs:
  # Find out more about other implicit resources you can reference within SAM
  HttpApi:
    Description: "API Gateway endpoint URL for Prod stage for Lotto function"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/lotto/WinningNumbers/{state}/{game}"
  CognitoRegion:
    Value: !Ref AWS::Region
  UserPoolId:
    Value: !Ref UserPool
  UserPoolWebClientId:
    Value: !Ref UserPoolWebClient
  UserPoolAuthDomain:
    Value: !Sub "${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com"
  LottoFunction:
    Description: "Lotto Lambda Function ARN"
    Value: !GetAtt LottoFunction.Arn
  LottoFunctionIamRole:
    Description: "Implicit IAM Role created for Lotto function"
    Value: !GetAtt LottoFunctionRole.Arn
