AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lotto-checker
Parameters:
  AppHostUrl:
    Type: String
    Description: URL where app will be hosted. To be added as a CORS allowed origin.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LottoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lotto/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          APP_HOST_URL: !Ref AppHostUrl
      Events:
        Lotto:
          Type: Api
          Properties:
            Path: /lotto/WinningNumbers/{state}/{game}
            Method: GET

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LottoApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/lotto/WinningNumbers/{state}/{game}"
  LottoFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt LottoFunction.Arn
  LottoFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LottoFunctionRole.Arn
