AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lotto-checker
Parameters:
  AppHostUrl:
    Type: String
    Description: URL where app will be hosted. To be added as a CORS allowed origin.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn

  LottoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lotto/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          APP_HOST_URL: !Ref AppHostUrl
      Events:
        Lotto:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /lotto/WinningNumbers/{state}/{game}
            Method: GET

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: LottoCheckerUserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false
  
  UserPoolWebClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: LottoCheckerFrontend
      GenerateSecret: false
      CallbackURLs:  
        - !Ref AppHostUrl
        - http://localhost:8080
      LogoutURLs:
        - !Ref AppHostUrl
        - http://localhost:8080

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref AWS::StackName
      UserPoolId: !Ref UserPool


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LottoApi:
    Description: "API Gateway endpoint URL for Prod stage for Lotto function"
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/lotto/WinningNumbers/{state}/{game}"
  CognitoRegion:
    Value: !Ref AWS::Region
  UserPoolId:
    Value: !Ref UserPool
  UserPoolWebClientId:
    Value: !Ref UserPoolWebClient
  UserPoolAuthDomain:
    Value: !Sub "${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com"
  LottoFunction:
    Description: "Lotto Lambda Function ARN"
    Value: !GetAtt LottoFunction.Arn
  LottoFunctionIamRole:
    Description: "Implicit IAM Role created for Lotto function"
    Value: !GetAtt LottoFunctionRole.Arn
