AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  LottoChecker Backend
Parameters:
  AppHostUrl:
    Type: String
    Description: URL where app will be hosted. To be added as a CORS allowed origin.
  AdminEmail:
    Type: String
    Description: Email ID for the initial admin user.

Globals:
  Function:
    Timeout: 3
    Handler: app.lambda_handler
    Runtime: python3.8

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: LottoChecker API
      CorsConfiguration:
        AllowMethods:
          - GET
          - PUT
        AllowHeaders:
          - "*"
        AllowOrigins:
          - "*"
      Auth:
        Authorizers:
          OAuth2Authorizer:
            AuthorizationScopes:
              - email
            JwtConfiguration:
              issuer: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}
              audience:
                - !Ref UserPoolWebClient
            IdentitySource: "$request.header.Authorization"
        DefaultAuthorizer: OAuth2Authorizer

  LotteryResultsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/lottery_results/
      Timeout: 5
      Environment:
        Variables:
          APP_HOST_URL: !Ref AppHostUrl
          TABLE_NAME: !Ref LotteryResultsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref LotteryResultsTable
      Events:
        Default:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /winningNumbers
            Method: GET
        GetWinningNumbers:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /winningNumbers/{game}
            Method: GET

  TicketsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/tickets/
      Environment:
        Variables:
          TICKETS_TABLE: !Ref TicketsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TicketsTable
      Events:
        ListTickets:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /tickets
            Method: GET
        PutTicket:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /tickets
            Method: PUT

  LotteryResultsEtlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/etl/
      Timeout: 30
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LotteryResultsTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt LotteryResultsEtlFailureTopic.TopicName
      Environment:
        Variables:
          TABLE_NAME: !Ref LotteryResultsTable
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: cron(1 5 ? * * *) # Every night at 11:01 PM CST (UTC-6)
            Enabled: True

  LotteryResultsEtlFailureTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Lottery Results ETL Failure
      Subscription:
        - Endpoint: !Ref AdminEmail
          Protocol: email
      TopicName: !Sub ${AWS::StackName}-LotteryResultsEtlFailure

  LotteryResultsEtlFailureDestination:
      Type: AWS::Lambda::EventInvokeConfig
      Properties:
        FunctionName: !Ref LotteryResultsEtlFunction
        Qualifier: "$LATEST"
        DestinationConfig:
          OnFailure:
            Destination: !Ref LotteryResultsEtlFailureTopic


  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${AWS::StackName}-UserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false
      AdminCreateUserConfig:
        InviteMessageTemplate:
          EmailSubject: !Sub Your temporary password for LottoChecker (${AWS::StackName})

  UserPoolWebClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub ${AWS::StackName}-frontend
      GenerateSecret: false
      CallbackURLs:
        - !Ref AppHostUrl
        - http://localhost:8080
      LogoutURLs:
        - !Ref AppHostUrl
        - http://localhost:8080
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref AWS::StackName
      UserPoolId: !Ref UserPool

  AdminUser:
    Type: AWS::Cognito::UserPoolUser
    Properties:
      UserPoolId: !Ref UserPool
      Username: !Ref AdminEmail
      DesiredDeliveryMediums:
        - EMAIL
      UserAttributes:
        - Name: email
          Value: !Ref AdminEmail

  TicketsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub ${AWS::StackName}-Tickets
      KeySchema:
        - AttributeName: UserId # user@example.com
          KeyType: HASH
        - AttributeName: DateRange # 2022-01-01#2022-01-30
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
        - AttributeName: DateRange
          AttributeType: S
      BillingMode: PAY_PER_REQUEST

  LotteryResultsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-LotteryResults
      KeySchema:
        - AttributeName: GameId
          KeyType: HASH
        - AttributeName: DrawingDate
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: GameId
          AttributeType: S
        - AttributeName: DrawingDate
          AttributeType: S
      BillingMode: PAY_PER_REQUEST

Outputs:
  # Find out more about other implicit resources you can reference within SAM
  HttpApi:
    Description: API base URL for LottoChecker services.
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com
  UserPoolRegion:
    Value: !Ref AWS::Region
  UserPoolId:
    Value: !Ref UserPool
  UserPoolWebClientId:
    Value: !Ref UserPoolWebClient
  UserPoolAuthDomain:
    Value: !Sub ${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com
