name: 'Save stack outputs'
description: 'Save CloudFormation stack outputs to env vars'
inputs:
  stack-name:
    description: 'Name of stack to save outputs from.'
    required: true
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: |
        aws cloudformation describe-stacks --stack-name lottochecker-fe-$STACK_NAME_SUFFIX \
          --query "Stacks[0].Outputs[] \
          > .cf_outputs.json
      shell: bash
    - run: | 
        while read -r variable; do
          key=$(jq -r '.OutputKey' <<< $variable)
          value=$(jq -r '.OutputValue' <<< $variable)
          echo "$key=$value"
          echo "$key=$value" >> $GITHUB_ENV
        done <<< $(jq -c '.[]' .cf_outputs.json)
        rm .cf_outputs.json
      shell: bash
