name: Save stack outputs
author: puremcc
description: Save CloudFormation stack outputs to env vars
inputs:
  stack-name:
    description: Name of stack to save outputs from.
    required: true
runs:
  using: "composite"
  steps:
    - name: Get outputs from stack
      shell: bash
      run: |
        aws cloudformation describe-stacks --stack-name ${{ inputs.stack-name }} \
          --query "Stacks[0].Outputs[]" \
          > /tmp/.cf_outputs.json

    - name: Parse outputs to env vars
      shell: bash
      run: |
        echo
        echo Saving outputs from stack \'${{ inputs.stack-name }}\' to the following env vars:
        while read -r variable; do
          key=$(jq -r '.OutputKey' <<< $variable)
          value=$(jq -r '.OutputValue' <<< $variable)
          echo "$key=$value"
          echo "$key=$value" >> $GITHUB_ENV
        done <<< $(jq -c '.[]' /tmp/.cf_outputs.json)
        rm /tmp/.cf_outputs.json
