name: Feature Development

on:
  push:
    branches: ["feature**"]
  delete:
    branches: ["feature**"]
  workflow_dispatch:

jobs:
  build:
    name: Build & Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build & Package artifacts
        uses: ./.github/actions/build
        with:
          artifacts-bucket: ${{ secrets.ARTIFACT_BUCKET }}

  deploy-feature:
    # this stage is triggered only for feature branches (feature*),
    # which will build the stack and deploy to a stack named with branch name.
    if: startsWith(github.ref, 'refs/heads/feature')
    needs: [build]
    runs-on: ubuntu-latest
    name: Deploy to Feature
    environment: feature
    steps:
      - uses: actions/checkout@v2

      - name: Set STACK_NAME_SUFFIX
        run: echo STACK_NAME_SUFFIX=$(date "+%Y%m%d-%H%M%S") >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to feature environment
        uses: ./.github/actions/deploy
        with:
          stack-name-suffix: ${{ env.STACK_NAME_SUFFIX }}
          artifact-bucket: ${{ secrets.ARTIFACT_BUCKET }}
          admin-email: ${{ secrets.ADMIN_EMAIL }}

  delete-feature:
    if: startsWith(github.event.ref, 'feature') && github.event_name == 'delete'
    needs: deploy-feature
    runs-on: ubuntu-latest
    name: Delete Feature
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Delete feature branch stack
        run: |
          sam delete \
              --stack-name lottochecker-$STACK_NAME_SUFFIX \
              --no-prompts
          sam delete \
              --stack-name lottochecker-fe-$STACK_NAME_SUFFIX \
              --no-prompts
