name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build backend (dev)
        run: |
          echo "Building the backend . . ."
          cd backend || exit 1
          sam build

      - name: Install frontend dependencies
        run: |
          cd frontend || exit 1
          npm install -g
          npm install -g @vue/cli-service

      - name: Build frontend (dev)
        run: |
          echo "Building the frontend . . ."
          cd frontend || exit 1
          vue-cli-service build

      - name: Deploy backend (dev)
        run: |
          echo "Deploying the backend . . ."
          cd backend || exit 1
          sam deploy --config-env development \
              --parameter-overrides "AppHostUrl=${{ secrets.APP_HOST_URL }}"

      - name: Deploy frontend (dev)
        run: |
          echo "Deploying the frontend . . ."
          cd frontend || exit 1
          aws s3 sync \
              --delete dist/ "s3://${{ secrets.BUCKET_NAME }}" \
          aws cloudfront create-invalidation \
              --distribution-id "${{ secrets.DISTRIBUTION_ID }}" \
              --paths "/*" \
