name: LottoChecker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build & Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build & Package artifacts
        uses: ./.github/actions/build
        with:
          artifacts-bucket: ${{ secrets.ARTIFACT_BUCKET }}

  deploy-dev:
    if: github.event_name == 'push'
    name: Deploy to Dev
    needs: build
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Dev
        uses: ./.github/actions/deploy
        with:
          stack-name-suffix: dev
          artifact-bucket: ${{ secrets.ARTIFACT_BUCKET }}
          admin-email: ${{ secrets.ADMIN_EMAIL }}
          website-url: ${{ secrets.WEBSITE_URL }}
          acm-certificate-arn: ${{ secrets.ACM_CERTIFICATE_ARN }}

  deploy-prod:
    if: github.event_name == 'push'
    name: Deploy to Prod
    needs: deploy-dev
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Prod
        uses: ./.github/actions/deploy
        with:
          stack-name-suffix: prod
          artifact-bucket: ${{ secrets.ARTIFACT_BUCKET }}
          admin-email: ${{ secrets.ADMIN_EMAIL }}
          website-url: ${{ secrets.WEBSITE_URL }}
          acm-certificate-arn: ${{ secrets.ACM_CERTIFICATE_ARN }}
