name: LottoChecker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build backend (dev)
        working-directory: backend
        run: sam build

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build:frontend

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact-frontend
          path: frontend/dist/
          if-no-files-found: error
  
  deploy-dev:
    name: Deploy to Dev
    needs: build
    environment: dev
    env:
      ENV_PREFIX: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy backend (dev)
        working-directory: backend
        run: |
          sam deploy --config-env development \
              --stack-name ${{ secrets.DEPLOY_STACK_NAME }} \
              --s3-bucket ${{ secrets.DEPLOY_ARTIFACT_BUCKET }} \
              --s3-prefix $ENV_PREFIX \
              --region ${{ secrets.DEPLOY_REGION }} \
              --no-fail-on-empty-changeset
              --no-confirm-changeset \
              --capabilities CAPABILITY_IAM \
              --parameter-overrides "AppHostUrl=${{ secrets.APP_HOST_URL }}"

      - name: Deploy frontend (dev)
        working-directory: frontend
        run: |
          aws s3 sync \
              --delete dist/ "s3://${{ secrets.BUCKET_NAME }}"
          aws cloudfront create-invalidation \
              --distribution-id "${{ secrets.DISTRIBUTION_ID }}" \
              --paths "/*" \
